resources:
- cryptochords-web-deployment.yaml
- cryptochords-web-service.yaml
- cryptochords-web-ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: hemilabs/cryptochords-web:latest
  newName: hemilabs/cryptochords-web
  newTag: 1.0.10
namespace: cryptochords-staging
