apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptochords-web
  labels:
    app: cryptochords-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptochords-web
  template:
    metadata:
      labels:
        app: cryptochords-web
    spec:
      containers:
      - name: cryptochords-web
        image: hemilabs/cryptochords-web:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_WEBSERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cryptochords-config
              key: VITE_API_WEBSERVICE_URL
        - name: VITE_USE_API_MOCK
          valueFrom:
            configMapKeyRef:
              name: cryptochords-config
              key: VITE_USE_API_MOCK
      imagePullSecrets:
      - name: dockerhub-secret
    