name: '[cryptochords] dockerhub web push'

on:
  push:
    tags:
      - 'v*'

jobs:
  dockerhubpush:
    name: '[cryptochords] dockerhub web push'
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push cryptochords-web
        uses: docker/build-push-action@v3
        with:
          tags: hemilabs/cryptochords-web:${{ steps.vars.outputs.tag }}
          context: "{{defaultContext}}"
          file: "Dockerfile.web"
          push: true
