apiVersion: v1
kind: Service
metadata:
  name: cryptochords-api-service
spec:
  type: ClusterIP # Use NodePort or ClusterIP if you don't have a LoadBalancer provider.
  ports:
    - name: http-testnet
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: cryptochords-api
